ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('ProyectoWebApp/', include('ProyectoWebApp.urls'))
    path('', include('ProyectoWebApp.urls')), #el punto de entrada sera proyectowebapp
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('autenticacion/',include("autenticacion.urls")),
    path('pedidos/',include("pedidos.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
        path('',views.blog, name="Blog"),
        path('categoria/<int:categoria_id>/',views.categoria,name='Categoria'),
]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>",views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>",views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>",views.restar_producto, name="restar"),
    path("limpiar/<int:producto_id>",views.limpiar_carro, name="limpiar"),
]

tienda/urls.py
from django.urls import path
from . import views

app_name = "tienda"

urlpatterns = [
        path('',views.tienda, name="Tienda"),
        path('categoria/<int:categoria_id>/',views.categoria,name='Categoria'),
]

tienda/models.py
from django.db import models

class CategoriaProd(models.Model):
	nombre=models.CharField(max_length=50)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	
	class Meta:
		verbose_name='Categoria'
		verbose_name_plural='Categorias'
		
	def __str__(self):
		return self.nombre
	
class Producto(models.Model):
	nombre=models.CharField(max_length=50)
	categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
	imagen=models.ImageField(upload_to="tienda", null=True, blank=True,default='default.jpg')
	precio=models.FloatField()
	disponibilidad=models.BooleanField(default=True)
	created=models.DateTimeField(auto_now_add=True,verbose_name="fecha de creacion")
	updated=models.DateTimeField(auto_now=True,verbose_name="fecha de actualizacion")

	class Meta:
		verbose_name='Producto'
		verbose_name_plural='Productos'
		
	def __str__(self):
		return self.nombre

tienda/views.py
from django.shortcuts import render

from tienda.models import Producto, CategoriaProd

def tienda(request):
    productos=Producto.objects.all()
    categorias=CategoriaProd.objects.all()
    return render(request,"tienda/tienda.html",{"productos":productos,"categorias":categorias})

def categoria(request,categoria_id):
    categoria=CategoriaProd.objects.get(id=categoria_id)
    productos=Producto.objects.filter(categorias=categoria)
    categorias=CategoriaProd.objects.all()
    return render(request, 'tienda/categoria.html',{'productos':productos,'categorias':categorias})

tienda/templates/tienda/categoria.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}


{% block content %}

<div class="container">


  <div class="row">

  {% for producto in productos %}

  <div class="col-md-3">

  <div class="card" style="width: 100%;margin: 5px 5px;">
    <img class="card-img-top" src="{{producto.imagen.url}}">

    <div class="card-body" style="text-align: center;">
      <h7 class="card-title">{{producto.nombre}}</h7>
      <p class="card-text">$&nbsp;{{producto.precio}}</p>
    </div><!--card-body que se cierra-->
    
  </div><!--card que se cierra-->

  </div><!--col que se cierra-->

  {% endfor %}

  </div><!--row que se cierra-->

</div><!--container que se cierra-->


<section>


  <div style="text-align:center;color:white;margin:auto; width:75%;">
  <p>Categorias: 
  {% for categoria in categorias %}
  <a href="{% url 'tienda:Categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}}</a>&nbsp;&nbsp;&nbsp;
  {% endfor %}
  </p>
  </div>

</section>


{% endblock %}

tienda/templates/tienda/tienda.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}


{% block content %}

<div class="container">

  <div style="float:right;">
  {% if request.user.is_authenticated %}
    {% include "carro/widget.html" %}
  {% else %}
    </br>
    <div class="alert alert-danger text-center">Logueate para ver el carro</div>
  {% endif %}
  </div>

  <div class="row">

  {% for producto in productos %}

  <div class="col-md-3">

  <div class="card" style="width: 100%;margin: 5px 5px;">
    <img class="card-img-top" src="{{producto.imagen.path}}">
			      <!--"{{producto.imagen.url}}"--!>

    <div class="card-body" style="text-align: center;">
      <h7 class="card-title">{{producto.nombre}}</h7>
      <p class="card-text">$&nbsp;{{producto.precio}}</p>
    </div><!--card-body que se cierra-->

    <div class="card-footer text-center">
       <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
    </div><!--cierre card-footer-->

  </div><!--card que se cierra-->

  </div><!--col que se cierra-->

  {% endfor %}

  </div><!--row que se cierra-->

</div><!--container que se cierra-->


<section>


  <div style="text-align:center;color:white;margin:auto; width:75%;">
  <p>Categorias: 
  {% for categoria in categorias %}
  <a href="{% url 'tienda:Categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}}</a>&nbsp;&nbsp;&nbsp;
  {% endfor %}
  </p>
  </div>

</section>


{% endblock %}