ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('ProyectoWebApp/', include('ProyectoWebApp.urls'))
    path('', include('ProyectoWebApp.urls')), #el punto de entrada sera proyectowebapp
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('autenticacion/',include("autenticacion.urls")),
    path('pedidos/',include("pedidos.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
        path('',views.blog, name="Blog"),
        path('categoria/<int:categoria_id>/',views.categoria,name='Categoria'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
	nombre=models.CharField(max_length=51)
	created=models.DateTimeField(auto_now_add=True,verbose_name="fecha de creacion")
	updated=models.DateTimeField(auto_now=True,verbose_name="fecha de creacion")
	
	class Meta:
		verbose_name='categoria'
		verbose_name_plural='categorias'
		
	def __str__(self):
		return self.nombre
	
	
class Post(models.Model):
	titulo=models.CharField(max_length=50)
	contenido=models.CharField(max_length=50)
	imagen=models.ImageField(upload_to='blog',null=True, blank=True,default='default.jpg')
	autor=models.ForeignKey(User, on_delete=models.CASCADE)
	categorias=models.ManyToManyField(Categoria)
	created=models.DateTimeField(auto_now_add=True,verbose_name="fecha de creacion")
	updated=models.DateTimeField(auto_now=True,verbose_name="fecha de creacion")

	class Meta:
		verbose_name='post'
		verbose_name_plural='posts'
		
	def __str__(self):
		return self.titulo

blog/views.py
from django.shortcuts import render

from blog.models import Post,Categoria

def blog(request):
    posts=Post.objects.all()
    categorias=Categoria.objects.all()
    return render(request,"blog/blog.html",{"posts":posts,"categorias":categorias})

def categoria(request,categoria_id):
    categoria=Categoria.objects.get(id=categoria_id)
    posts=Post.objects.filter(categorias=categoria)
    categorias=Categoria.objects.all()
    return render(request, 'blog/categoria.html',{'posts':posts,'categorias':categorias})

blog/templates/blog/blog.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}


{% block content %}

{% for post in posts %}

<section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width: 50%;">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-lower">{{post.titulo}}</span>
            <span class="section-heading-upper">{{post.contenido}}</span>
          </h2>
          <div style="text-align:left;font-size: 0.8em;">Autor: {{post.autor}}</div>
        </div>
      </div>
    </div>
</section>

{% endfor %}
<section>


  <div style="text-align:center;color:white;margin:auto; width:75%;">
  <p>Categorias: 
  {% for categoria in categorias %}
  <a href="{% url 'blog:Categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}}</a>&nbsp;&nbsp;&nbsp;
  {% endfor %}
  </p>
  </div>

</section>
{% endblock %}

blog/templates/blog/categoria.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}


{% block content %}

{% for post in posts %}

<section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width: 50%;">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-lower">{{post.titulo}}</span>
            <span class="section-heading-upper">{{post.contenido}}</span>
          </h2>
          <div style="text-align:left;font-size: 0.8em;">Autor: {{post.autor}}</div>
        </div>
      </div>
    </div>
</section>

{% endfor %}

<section>

  <div style="text-align:center;color:white;margin:auto; width:75%;">

    <p>Categorias: 
    {% for categoria in categorias %}
    <a href="{% url 'blog:Categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}}</a>&nbsp;&nbsp;&nbsp;
    {% endfor %}
    </p>

  </div>

</section>

{% endblock %}