ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('ProyectoWebApp/', include('ProyectoWebApp.urls'))
    path('', include('ProyectoWebApp.urls')), #el punto de entrada sera proyectowebapp
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
    path('autenticacion/',include("autenticacion.urls")),
    path('pedidos/',include("pedidos.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoWebApp/urls.py
from django.urls import path
from ProyectoWebApp import views

urlpatterns = [
    path('',views.home, name="Home"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
        path('',views.blog, name="Blog"),
        path('categoria/<int:categoria_id>/',views.categoria,name='Categoria'),
]

tienda/urls.py
from django.urls import path
from . import views

app_name = "tienda"

urlpatterns = [
        path('',views.tienda, name="Tienda"),
        path('categoria/<int:categoria_id>/',views.categoria,name='Categoria'),
]

ProyectoWebApp/models.py
from django.db import models

# Create your models here.

ProyectoWebApp/views.py
from django.shortcuts import render

from carro.carro import Carro

def home(request):
    carro = Carro(request)
    return render(request,'ProyectoWebApp/home.html')

ProyectoWebApp/templates/ProyectoWebApp/base.html
<html>

<head>

  {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'ProyectoWebApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'ProyectoWebApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Gestión de Pedidos</span>
      </h1>

      <div style="color:white;text-align: right;margin-right: 100px;">
        
        {% if user.is_authenticated %}
          Hola {{user.username}} &nbsp;&nbsp; <a href="{% url 'cerrar_sesion' %}"style="color:white;">Cerrar Sesion</a>
        {% else %}
          <a href="{% url 'logear' %}" style="color:white;">Login</a> &nbsp;&nbsp; <a href="{% url 'registro' %}" style="color:white;">Registrate</a>
        {% endif %}

      </div>

 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Home' %}">Gestión de Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/servicios/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Servicios' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path|slice:':8' == '/tienda/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'tienda:Tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contacto/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Contacto' %}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path|slice:':6' == '/blog/' %}active{% endif %} px-lg-4">
            <!--el slice:6 es para que le aplique el subrayado a todas las paginas cuyos 6 caracteres sean /blog/-->
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:Blog' %}">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>


<!-- contenido cambiante -->
{% block content %}
{% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'ProyectoWebApp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ProyectoWebApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

ProyectoWebApp/templates/ProyectoWebApp/home.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}